# Generated by Codex on 2026-05-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='last_accessed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
