# Generated by Django 5.2.14 on 2026-05-17 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_caso_last_accessed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoAnalista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabecalho', models.TextField(blank=True, default='POLÍCIA CIVIL DO DISTRITO FEDERAL\nCORF — Coordenadoria de Repressão aos Crimes Cibernéticos')),
                ('assinatura_nome', models.CharField(blank=True, max_length=150)),
                ('assinatura_cargo', models.CharField(blank=True, max_length=150)),
                ('assinatura_orgao', models.CharField(blank=True, default='CORF/PCDF', max_length=150)),
                ('logo', models.ImageField(blank=True, upload_to='configuracoes/logos/')),
                ('incluir_info_tecnica', models.BooleanField(default=True)),
                ('intervalo_screenshot', models.IntegerField(choices=[(0, 'Desativado'), (5, 'A cada 5 segundos'), (10, 'A cada 10 segundos'), (30, 'A cada 30 segundos')], default=0)),
                ('pasta_padrao', models.CharField(blank=True, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analista', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração do Analista',
                'verbose_name_plural': 'Configurações dos Analistas',
            },
        ),
    ]
